{% set version = "1.2.0" %}
{% set llvm_version = 13 %}

package:
  name: python-wasmer-split

source:
  url: https://github.com/wasmerio/wasmer-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8e32674dfe679e3bec1228eeb514f78b40b6fb8d8655a69765b405cbfe9c8682
  patches:
    - 0000-deprecated-maturin-metadata.diff

build:
  number: 1
  skip: true  # [py<38]

outputs:
  - name: python-wasmer
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    script: build_wasmer.bat  # [win]
    build:
      run_exports:
        - python-wasmer
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - sysroot_linux-64 2.17  # [linux64]
        - cargo-bundle-licenses
      host:
        - python
        - pip
        - maturin
        - lld
        - pytest
        - zlib  # [linux]
      run:
        - python
        - lld
    test:
      imports:
        - wasmer

  - name: python-wasmer-compiler-cranelift
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    script: build_wasmer.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - python
        - pip
        - maturin
        - pytest
        - pytest-benchmark
        - python-wasmer
      run:
        - python-wasmer
        - python
    test:
      imports:
        - wasmer_compiler_cranelift

  - name: python-wasmer-compiler-singlepass
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - python
        - pip
        - maturin
        - pytest
        - python-wasmer
      run:
        - python-wasmer
        - python
    test:
      imports:
        - wasmer_compiler_singlepass  # [unix]

  - name: python-wasmer-compiler-llvm
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses
      host:
        - python
        - pip
        - maturin
        - pytest
        - pytest-benchmark
        - clang
        - llvmdev {{ llvm_version }}.*
        - python-wasmer
        - python-wasmer-compiler-cranelift
        - zlib  # [linux]
      run:
        - clang
        - libffi
        - libllvm{{ llvm_version }}
        - libstdcxx-ng  # [linux64]
        - python-wasmer
        - python
    test:
      imports:
        - wasmer_compiler_llvm  # [unix]

about:
  home: https://wasmer.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebAssembly runtime for Python
  doc_url: https://docs.wasmer.io
  dev_url: https://github.com/wasmerio/wasmer

extra:
  feedstock-name: python-wasmer-split
  recipe-maintainers:
    - atrawog
    - wolfv
    - bollwyvl
